import Footer from '@/components/footer'
import ReduxProvider from '@/components/redux'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    default: 'Ashishkumar Vishwakarma',
    template: '%s | AVishwakarma',
  },
  description: `I'm a passionate frontend developer with a strong
  foundation in engineering. With a deep love for clean and
  user-friendly design, I transform ideas into beautifully
  crafted, responsive web experiences.`,
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="!scroll-smooth" lang="en" data-theme="dracula">
      <body className={inter.className}>
        <ReduxProvider>
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              style: {
                borderRadius: '10px',
                background: 'hsl(var(--b1))',
                color: '(var(--bc))',
              },
            }}
          />
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  )
}
