import Footer from '@/components/footer'
import ReduxProvider from '@/components/redux'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'
import { Toaster } from 'react-hot-toast'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  manifest: '/manifest.json',
  title: {
    default: 'Ashishkumar Vishwakarma',
    template: '%s | AVishwakarma',
  },
  description: `I'm a passionate frontend developer with a strong
  foundation in engineering. With a deep love for clean and
  user-friendly design, I transform ideas into beautifully
  crafted, responsive web experiences.`,
  icons: {
    icon: '/favicon-32x32.png',
    shortcut: '/favicon-32x32.png',
    apple: '/favicon-32x32.png',
    other: {
      rel: 'apple-touch-icon-precomposed',
      url: '/apple-touch-icon-precomposed.png',
    },
  },
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="!scroll-smooth" lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader
            color="hsl(var(--primary))"
            height={3}
            showSpinner={false}
          />
          <ReduxProvider>
            {children}
            <Toaster
              position="top-right"
              toastOptions={{
                style: {
                  borderRadius: 'var(----radius)',
                  background: 'hsl(var(--background))',
                  color: '(var(--foreground))',
                },
              }}
            />
            <Footer />
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
